export { default as ReporteAmbiente } from './ReporteAmbiente.vue'
export { default as ReporteUso } from './ReporteUso.vue'
export { default as ReporteUsuario } from './ReporteUsuario.vue'
export { default as ReportePDF } from './ReportePDF.vue'
export { default as ReporteUsuarioTabla } from './ReporteUsuarioTabla.vue'
export { default as ReporteAmbientePDF } from './ReporteAmbientePDF.vue'
